name = "MLFS"
uuid = "134ce997-ef8c-4161-ad1c-b6b659cb0a92"
authors = ["thautwarm <twshere@outlook.com> and contributors"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
PrettyPrint = "8162dcfd-2161-5ef2-ae6c-7681170c5f98"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"

[compat]
MLStyle = "0.4"
PrettyPrint = "0.2"
Setfield = "0.7"
DataStructures = "~0.17.1, 0.18.0"
julia = "^1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
